import { Router } from "express";

import {
  signup,
  login,
  getUserInfo,
  updateProfile,
  addProfileImage,
  removeProfileImage,
  logout,
} from "../controllers/AuthController.js";
import { verifyToken } from "../middlewares/AuthMiddleware.js";
import multer from "multer";
import path from "path";

// Express cannot read multipart/form-data file uploads by itself,
// so multer parses the uploaded file and makes it available on req.file, then Cloudinary
// stores it in the cloud. Normal JSON cannot send files, so we use multipart/form-data.
// JSON = data only ==> express.json()
// Multipart = data + files ==> multer({})

// Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryabc123 ==> no need to mention.
// Axios (and most browsers) will automatically set it correctly with the boundary when you pass a FormData object:
// await apiClient.post(UPLOAD_FILE_ROUTE, formData, { withCredentials: true });

const authRoutes = Router();

// cwd ==> It is the folder where your Node.js process is currently running.

console.log("current working directory from AuthRoutes ==> ", process.cwd()); //  D:\clones\chat\server
console.log(`path.resolve("test1") ==> `, path.resolve("test1")); // D:\clones\chat\server + \test1 ==> D:\clones\chat\server\test1

const upload = multer({ dest: "uploads/profiles/" });

// is equivalent to Multer internally resolving the path like this : path.resolve(process.cwd(), "uploads/profiles/");
// D:\clones\chat\server\uploads\profiles\

// const upload = multer({ dest: "uploads/profiles" });
// / means a path separator in file systems and URLs , ending / says the path ends at the "profiles" folder.

// Attach file info to req.file
// {
//   fieldname: 'profile',
//   originalname: 'photo.jpg',
//   encoding: '7bit',
//   mimetype: 'image/jpeg',
//   destination: 'uploads/profiles',
//   filename: 'a1b2c3d4', // The filename is the name Multer gives the file when it saves it.
//   path: 'uploads/profiles/a1b2c3d4', // random filename generated by Multer
//   size: 23456
// }

authRoutes.post("/signup", signup);
authRoutes.post("/login", login);
authRoutes.post("/logout", logout);

authRoutes.get("/user-info", verifyToken, getUserInfo);

authRoutes.post("/update-profile", verifyToken, updateProfile);

authRoutes.post(
  "/add-profile-image",
  verifyToken,
  upload.single("profile-image"), // “Before controller runs, take the uploaded file, store it on disk, and attach its info to req.file”
  // "profile-image" → must match the frontend input name
  // <input type="file" name="profile-image" />
  addProfileImage,
);
authRoutes.delete("/remove-profile-image", verifyToken, removeProfileImage);

export default authRoutes;

// For REST API route naming, common convention is :
// use kebab-case , Instead of : POST /create-user ==> POST /users , HTTP method already acts like the verb.

// multer does not automatically create the directory when using dest.
// If uploads/profiles/ doesn't exist, the upload will fail with an error such as:

// ENOENT: no such file or directory

// So we should create the folder yourself before uploading:

// Or use multer.diskStorage() to have more control over where and how files are stored.
