import { Router } from "express";

import {
  signup,
  login,
  getUserInfo,
  updateProfile,
  addProfileImage,
  removeProfileImage,
} from "../controllers/AuthController.js";
import { verifyToken } from "../middlewares/AuthMiddleware.js";
import multer from "multer";

// Express cannot read multipart/form-data file uploads by itself,
// so multer parses the uploaded file and makes it available as req.file, then Cloudinary
// stores it in the cloud. Normal JSON cannot send files, so we use multipart/form-data.
// JSON = data only , express.json()
// Multipart = data + files , multer

const authRoutes = Router();

const upload = multer({ dest: "uploads/profiles/" });
// Attach file info to req.file
// {
//   fieldname: 'profile',
//   originalname: 'photo.jpg',
//   encoding: '7bit',
//   mimetype: 'image/jpeg',
//   destination: 'uploads/profiles/',
//   filename: 'a1b2c3d4',
//   path: 'uploads/profiles/a1b2c3d4', // random filename generated by Multer
//   size: 23456
// }

authRoutes.post("/signup", signup);
authRoutes.post("/login", login);
authRoutes.get("/user-info", verifyToken, getUserInfo);
authRoutes.post("/update-profile", verifyToken, updateProfile);
authRoutes.post(
  "/add-profile-image",
  verifyToken,
  upload.single("profile-image"),
  // "profile-image" → must match the frontend input name
  // <input type="file" name="profile-image" />
  addProfileImage,
);
authRoutes.delete("/remove-profile-image", verifyToken, removeProfileImage);

export default authRoutes;
