import winston from "winston";

const logger = winston.createLogger({
  level: "info",
  format: winston.format.json(),
  transports: [
    new winston.transports.File({
      filename: "logs/error.log",
      level: "error",
    }),
    new winston.transports.File({
      filename: "logs/combined.log",
    }),
  ],
});

// console logs in dev
if (process.env.NODE_ENV !== "production") {
  logger.add(
    new winston.transports.Console({
      format: winston.format.simple(),
    }),
  );
}

export default logger;

// Morgan captures HTTP requests, Winston stores and manages all logs (requests + errors + metrics).
// Morgan = CCTV camera
// Winston = company database + HR system

// log is generated by Morgan automatically
// Then your stream sends it to Winston
