import winston from "winston";

// generated by morgan and store by winston

const logger = winston.createLogger({
  level: "info", // minimum log level is info
  // “Start logging from info level and above (more serious logs), ignore low-level noise.”
  format: winston.format.json(),

  // transports: [
  //   new winston.transports.File({
  //     filename: "logs/error.log",
  //     level: "error", // Only error logs go here.
  //   }),

  //   new winston.transports.File({
  //     filename: "logs/combined.log", // Everything (info + warn + error)
  //   }),
  // ],

});


// It tells Winston : “Also print logs to terminal (console)”
//  new winston.transports.Console({}) vs  new winston.transports.File({})
if (process.env.NODE_ENV !== "prod") {
  logger.add(
    new winston.transports.Console({
      format: winston.format.simple(),
      // If you don’t specify level, Winston uses : level: "info" (from logger config)
    }),
  );
}

export default logger;

// Morgan captures HTTP requests, Winston stores and manages all logs (requests + errors + metrics).
// Morgan = CCTV camera
// Winston = company database + HR system

// log is generated by Morgan automatically
// Then your stream sends it to Winston

// -------------------------------------------------------------------------------------

// There are 2 levels of quotes

// 1️⃣ JSON outer quotes
// "message": " .... "

// 👉 This defines the string itself

// 2️⃣ Inner quotes (your log)
// "GET /api/v1/auth/user-info HTTP/1.1"

// 👉 This is data inside the string

// ❌ Problem without \ (backslash)
// "message": " "GET /api/v1/auth/user-info HTTP/1.1" "

// sol :

// "message": "  \" GET /api/v1/auth/user-info HTTP/1.1 \"  "

// Now JSON understands:

// outer quotes → string boundary
// \" → just a quote inside

// backslash \ ==> “this quote is part of text, not the end of the string.”

// error  (highest importance)
// warn
// info   ← minimum level you set
// http
// verbose
// debug
// silly  (lowest importance)
